[versions]
agp = "9.0.0"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"
firebasePlugin = "4.4.4"
googleServices = "4.4.4"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.3"
constraintlayout = "2.2.1"
playServicesMeasurementApi = "23.0.0"
firebaseBom = "34.8.0"
crashlytics = "3.0.6"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
play-services-measurement-api = { group = "com.google.android.gms", name = "play-services-measurement-api", version.ref = "playServicesMeasurementApi" }
#androidx-multidex = { module = "androidx.multidex:multidex", version = "2.0.1" }
eventbus = { module = "org.greenrobot:eventbus", version = "3.3.1" }
slidetoact = { module = "com.ncorti:slidetoact", version = "2.1.0" }
lottie = { module = "com.airbnb.android:lottie", version = "6.7.1" }
roundedimageview = { module = "com.makeramen:roundedimageview", version = "2.3.0" }

google-gson = { module = "com.google.code.gson:gson", version = "2.13.2" }

retrofit = { module = "com.squareup.retrofit2:retrofit", version = "3.0.0" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version = "3.0.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.2" }

room-runtime = { module = "androidx.room:room-runtime", version = "2.8.4" }
room-ktx = { module = "androidx.room:room-ktx", version = "2.8.4" }
compiler = { module = "androidx.room:room-compiler", version = "2.8.4" }

lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version = "2.10.0" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version = "2.10.0" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.10.0" }

glide = { module = "com.github.bumptech.glide:glide", version = "5.0.5" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version = "5.0.5" }

play-services-ads = { module = "com.google.android.gms:play-services-ads", version = "24.9.0" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
#org-jetbrains-kotlin-kapt    = { id = "org.jetbrains.kotlin.kapt",    version.ref = "kotlin" }
com-android-library = { id = "com.android.library", version.ref = "agp" }
googleplugin = { id = "com.google.gms.google-services", version.ref = "googleServices" }
crashlyticsplugin = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }

